// Mocks generated by Mockito 5.4.6 from annotations
// in fsg/test/glsl_shader_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_angle/flutter_angle.dart' as _i2;
import 'package:fsg/glsl_shader.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProgram_0 extends _i1.SmartFake implements _i2.Program {
  _FakeProgram_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUniformLocation_1 extends _i1.SmartFake
    implements _i2.UniformLocation {
  _FakeUniformLocation_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GlslShaderContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockGlslShaderContext extends _i1.Mock implements _i3.GlslShaderContext {
  MockGlslShaderContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic createShader(int? type) =>
      super.noSuchMethod(Invocation.method(#createShader, [type]));

  @override
  void shaderSource(dynamic shader, String? source) => super.noSuchMethod(
    Invocation.method(#shaderSource, [shader, source]),
    returnValueForMissingStub: null,
  );

  @override
  void compileShader(dynamic shader) => super.noSuchMethod(
    Invocation.method(#compileShader, [shader]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic getShaderParameter(dynamic shader, int? pname) => super.noSuchMethod(
    Invocation.method(#getShaderParameter, [shader, pname]),
  );

  @override
  _i2.Program createProgram() =>
      (super.noSuchMethod(
            Invocation.method(#createProgram, []),
            returnValue: _FakeProgram_0(
              this,
              Invocation.method(#createProgram, []),
            ),
          )
          as _i2.Program);

  @override
  void attachShader(_i2.Program? program, dynamic shader) => super.noSuchMethod(
    Invocation.method(#attachShader, [program, shader]),
    returnValueForMissingStub: null,
  );

  @override
  void linkProgram(_i2.Program? program) => super.noSuchMethod(
    Invocation.method(#linkProgram, [program]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic getProgramParameter(_i2.Program? program, int? pname) => super
      .noSuchMethod(Invocation.method(#getProgramParameter, [program, pname]));

  @override
  String? getProgramInfoLog(_i2.Program? program) =>
      (super.noSuchMethod(Invocation.method(#getProgramInfoLog, [program]))
          as String?);

  @override
  void deleteShader(dynamic shader) => super.noSuchMethod(
    Invocation.method(#deleteShader, [shader]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteProgram(_i2.Program? program) => super.noSuchMethod(
    Invocation.method(#deleteProgram, [program]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.UniformLocation getAttribLocation(_i2.Program? program, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getAttribLocation, [program, name]),
            returnValue: _FakeUniformLocation_1(
              this,
              Invocation.method(#getAttribLocation, [program, name]),
            ),
          )
          as _i2.UniformLocation);

  @override
  _i2.UniformLocation getUniformLocation(_i2.Program? program, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getUniformLocation, [program, name]),
            returnValue: _FakeUniformLocation_1(
              this,
              Invocation.method(#getUniformLocation, [program, name]),
            ),
          )
          as _i2.UniformLocation);

  @override
  void enableVertexAttribArray(int? index) => super.noSuchMethod(
    Invocation.method(#enableVertexAttribArray, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void checkError(String? label) => super.noSuchMethod(
    Invocation.method(#checkError, [label]),
    returnValueForMissingStub: null,
  );

  @override
  void uniform1f(_i2.UniformLocation? location, double? v0) =>
      super.noSuchMethod(
        Invocation.method(#uniform1f, [location, v0]),
        returnValueForMissingStub: null,
      );

  @override
  void uniform1i(_i2.UniformLocation? location, int? v0) => super.noSuchMethod(
    Invocation.method(#uniform1i, [location, v0]),
    returnValueForMissingStub: null,
  );

  @override
  void uniform2f(_i2.UniformLocation? location, double? v0, double? v1) =>
      super.noSuchMethod(
        Invocation.method(#uniform2f, [location, v0, v1]),
        returnValueForMissingStub: null,
      );

  @override
  void uniform3f(
    _i2.UniformLocation? location,
    double? v0,
    double? v1,
    double? v2,
  ) => super.noSuchMethod(
    Invocation.method(#uniform3f, [location, v0, v1, v2]),
    returnValueForMissingStub: null,
  );

  @override
  void uniform4f(
    _i2.UniformLocation? location,
    double? v0,
    double? v1,
    double? v2,
    double? v3,
  ) => super.noSuchMethod(
    Invocation.method(#uniform4f, [location, v0, v1, v2, v3]),
    returnValueForMissingStub: null,
  );

  @override
  void uniform4fv(_i2.UniformLocation? location, List<double>? value) =>
      super.noSuchMethod(
        Invocation.method(#uniform4fv, [location, value]),
        returnValueForMissingStub: null,
      );

  @override
  void uniformMatrix3fv(
    _i2.UniformLocation? location,
    bool? transpose,
    List<double>? value,
  ) => super.noSuchMethod(
    Invocation.method(#uniformMatrix3fv, [location, transpose, value]),
    returnValueForMissingStub: null,
  );

  @override
  void uniformMatrix4fv(
    _i2.UniformLocation? location,
    bool? transpose,
    List<double>? value,
  ) => super.noSuchMethod(
    Invocation.method(#uniformMatrix4fv, [location, transpose, value]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Program].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgram extends _i1.Mock implements _i2.Program {
  MockProgram() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [UniformLocation].
///
/// See the documentation for Mockito's code generation for more information.
class MockUniformLocation extends _i1.Mock implements _i2.UniformLocation {
  MockUniformLocation() {
    _i1.throwOnMissingStub(this);
  }
}
